### todo_ui.R --- 
## Filename: todo_ui.R
## Description: 
## Author: Noah Peart
## Created: Sat Oct 31 01:41:27 2015 (-0400)
## Last-Updated: Sun Nov  1 17:04:11 2015 (-0500)
##           By: Noah Peart
######################################################################

info <- '<p>All of the TODO stuff is generated by orgmode.  None of the .html files are
bundled with the app, so this link will only function after using
orgmode to process the documents in /org/.</p>'
  
bootstrapPage(
    HTML(info),
    a(href="/org/html/index.html", target="_blank", "Here")
)
